name: TRTT All In One

on:
  schedule:
    - cron: '0 2,8,11,14,16,20 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # GitHub-এ কোড পুশ করার পারমিশন দেওয়া হলো
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - run: pip install requests feedparser beautifulsoup4 google-api-python-client google-auth-httplib2 google-auth-oauthlib pyTelegramBotAPI facebook-sdk

      
      - name: Run Bot
        env:
          FB_PAGE_TOKEN: ${{ secrets.FB_PAGE_TOKEN }}
          FB_PAGE_ID: ${{ secrets.FB_PAGE_ID }}
          BLOGGER_ID: ${{ secrets.BLOGGER_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
        run: python automation.py
        
      - name: Save
        run: |
          git config --global user.name 'TRTT Bot'
          git config --global user.email 'bot@trtt.com'
          git pull origin main --rebase || true
          git add .
          git commit -m "auto" || true
          git push origin main || true
